# Generated by Django 3.0.5 on 2021-03-31 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('ทั่วไป', 'ทั่วไป'), ('ความรัก', 'ความรัก'), ('ปรึกษา', 'ปรึกษา'), ('การเรียน', 'การเรียน')], default='ทั่วไป', max_length=200)),
                ('user_id', models.IntegerField(blank=True, default=None)),
                ('picture', models.CharField(max_length=200, null=True)),
                ('pic_name', models.CharField(max_length=100)),
                ('like_count', models.BigIntegerField(default='0')),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('picture', models.CharField(default='picture', max_length=200)),
                ('pic_name', models.CharField(default='pic_name', max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
